sp500_index:
  outputs:

    dev:
      type: sqlite
      threads: 1
      database: sp500
      schema: 'main'
      schemas_and_paths:
        main: 'sp500.db'
      schema_directory: '${{ github.workspace }}'
      extensions:
        - '${{ github.workspace }}/crypto.arm64'

  target: dev
