name: piperider-ci

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  piperider-ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: download crypto library
        run: curl -LJO https://github.com/nalgeon/sqlean/releases/download/0.15.2/crypto.so

      - name: PipeRider CLI Action
        uses: InfuseAI/piperider-action@v0.4.1
        id: piperider
        env: 
          DBT_PROFILES_DIR: ${{ github.workspace }} 
